"""Backs the review server's Pipeline tab: read_config()/write_config() for
the editable criteria.json/rubric.md/profile/summary.md form, and
keyword_stats() for the keyword-effectiveness table computed from seen.db.

This used to be render_pipeline.py, which wrote a full standalone
pipeline.html (regenerated by hand after every criteria.json/rubric.md
edit). Folded into ftja.server instead: the server reads/writes these
files live, app.html renders and edits them client-side — nothing to
regenerate, and edits land immediately instead of round-tripping through
a skill invocation.
"""
import json
import os

from ftja.state import connect


def _read(path, default=""):
    return open(path).read() if os.path.exists(path) else default


def _read_json(path, default=None):
    if not os.path.exists(path):
        return default
    with open(path) as f:
        return json.load(f)


_DEFAULT_CRITERIA = {
    "search_terms": [], "location": "", "is_remote": True, "hours_old": 72,
    "results_wanted": 100, "exact_phrase_search": True, "languages": [],
    "exclude_keywords": [], "keywords": {"tier1": []},
}


def _profile_sources(project_dir: str) -> list[dict]:
    """Registered profile sources, defaulting to the two files setup already
    asks the user to place in profile/. The registry controls references only;
    it never deletes source files."""
    registry_path = f"{project_dir}/profile/sources.json"
    sources = _read_json(registry_path, None)
    if sources is None:
        sources = []
        for rel_path, label in (("profile/CV.pdf", "CV"), ("profile/portfolio.md", "Portfolio")):
            if os.path.exists(f"{project_dir}/{rel_path}"):
                sources.append({"path": rel_path, "label": label, "enabled": True})
    result = []
    for source in sources if isinstance(sources, list) else []:
        if not isinstance(source, dict) or not source.get("path"):
            continue
        rel_path = str(source["path"]).replace("\\", "/")
        absolute = os.path.abspath(os.path.join(project_dir, rel_path))
        result.append({
            "path": rel_path,
            "label": source.get("label") or os.path.basename(os.path.normpath(rel_path)),
            "kind": "folder" if source.get("kind") == "folder" or os.path.isdir(absolute) else "file",
            "enabled": source.get("enabled", True) is not False,
            "exists": os.path.exists(absolute),
        })
    return result


def read_config(project_dir: str = ".") -> dict:
    """Raw config for the Pipeline tab: criteria, shared rubric, profile
    summary, and a non-destructive registry of source files."""
    criteria = {**_DEFAULT_CRITERIA, **(_read_json(f"{project_dir}/criteria.json", {}) or {})}
    return {
        "criteria": criteria,
        "rubric_md": _read(f"{project_dir}/rubric.md", ""),
        "profile_md": _read(f"{project_dir}/profile/summary.md", ""),
        "profile_sources": _profile_sources(project_dir),
    }


def write_config(project_dir: str = ".", criteria: dict | None = None,
                  rubric_md: str | None = None, profile_md: str | None = None,
                  profile_sources: list[dict] | None = None):
    """Writes whichever of the three is provided — same effect as hand-editing
    the file, so nothing here git-commits; that stays a deliberate, separate
    step (see /ftja-tune's one-conversational-update-per-commit discipline)."""
    if criteria is not None:
        with open(f"{project_dir}/criteria.json", "w") as f:
            json.dump(criteria, f, ensure_ascii=False, indent=2)
            f.write("\n")
    if rubric_md is not None:
        with open(f"{project_dir}/rubric.md", "w") as f:
            f.write(rubric_md)
    if profile_md is not None:
        os.makedirs(f"{project_dir}/profile", exist_ok=True)
        with open(f"{project_dir}/profile/summary.md", "w") as f:
            f.write(profile_md)
    if profile_sources is not None:
        os.makedirs(f"{project_dir}/profile", exist_ok=True)
        clean_sources = []
        for source in profile_sources:
            if not isinstance(source, dict) or not source.get("path"):
                continue
            path = str(source["path"]).replace("\\", "/")
            if path.startswith("../") or "/../" in path:
                raise ValueError("profile source paths cannot traverse parent directories")
            clean_sources.append({
                "path": path,
                "label": str(source.get("label") or os.path.basename(os.path.normpath(path))),
                "kind": "folder" if source.get("kind") == "folder" or os.path.isdir(path) else "file",
                "enabled": source.get("enabled", True) is not False,
            })
        with open(f"{project_dir}/profile/sources.json", "w") as f:
            json.dump(clean_sources, f, ensure_ascii=False, indent=2)
            f.write("\n")


def keyword_stats(db_path: str = "seen.db") -> list[dict]:
    """Per tier1 keyword, across every job seen.db has a record for: how many
    times it matched, and how far those jobs got. A keyword with a lot of
    matches but zero stage2 passes is a candidate for removal; one that's
    rare but always leads to a pass is worth pointing tier1 weight at."""
    with connect(db_path) as conn:
        rows = conn.execute("SELECT t1_matched_keywords, status FROM seen_jobs WHERE t1_matched_keywords IS NOT NULL").fetchall()

    counts: dict[str, dict[str, int]] = {}
    for kw_json, status in rows:
        try:
            keywords = json.loads(kw_json) if kw_json else []
        except json.JSONDecodeError:
            keywords = []
        for kw in keywords:
            # status is always stage1_fail/stage2_fail/passed here — a row only
            # gets t1_matched_keywords once it clears Stage0's tier1 check, so
            # stage0_fail never appears (those jobs never reach mark_seen at all).
            c = counts.setdefault(kw, {"matched": 0, "passed": 0, "stage2_fail": 0, "stage1_fail": 0})
            c["matched"] += 1
            c[status] = c.get(status, 0) + 1

    stats = [{"keyword": kw, **c} for kw, c in counts.items()]
    stats.sort(key=lambda s: s["matched"], reverse=True)
    return stats
